Test Practice using Jest framework
blackpintz/js-test-practice pull request #1
Opened 2020-10-08 10:43 UTC by blackpintz

## Project Specifics.

1). Wrote tests for the following functions:

- capitalizeString(string).

- reverseString(string).

- calculator object.

- caesarCipher().

- arrayAnalsis(arr).

2020-10-08 12:54 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi @blackpintz! This is great! Your tests and challenge implementations look good. There are a few issues though. These include:
- [ ] Use ES6 import statements. There is a special note on how you can make this work with Jest at the bottom of the [Odin assignment](https://www.theodinproject.com/courses/javascript/lessons/testing-practice) page.
- [ ] Check out the comment below.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-10-08 12:54 UTC, trekab commented on calculator/calculator.js
> +}
Consider making use of a basic JS object (with key, value pairs). Otherwise, you may have to make use of a class constructor.

2020-10-12 18:23 UTC, shloch approved these changes
## Hello @blackpintz 

On the basis of your work done , former review and your improvements,

![calc](https://user-images.githubusercontent.com/40712459/95778623-6acce880-0cc0-11eb-8f91-6aff447c11f8.gif)

You have met the requirements for this project
Great job, Happy coding

2020-10-12 18:23 UTC, shloch commented on calculator/calculator.js
>  }
Goof job with implementing the updates

2020-10-13 09:28 UTC, merged